{{- if and .Values.paperless.apiToken.value (not .Values.paperless.apiToken.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless-wsd-bridge.fullname" . }}-paperless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "paperless-wsd-bridge.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.paperless.apiToken.existingSecretKey }}: {{ .Values.paperless.apiToken.value | quote }}
{{- end }}
